- id: doi:10.1126/science.aah4307
  type: paper
  description: Some cancers evade targeted therapies through a mechanism known as lineage plasticity, whereby tumor cells acquire phenotypic characteristics of a cell lineage whose survival no longer depends on the drug target. We use in vitro and in vivo human prostate cancer models to show that these tumors can develop resistance to the antiandrogen drug enzalutamide by a phenotypic shift from androgen receptor (AR)–dependent luminal epithelial cells to AR-independent basal-like cells. This lineage plasticity is enabled by the loss of TP53 and RB1 function, is mediated by increased expression of the reprogramming transcription factor SOX2, and can be reversed by restoring TP53 and RB1 function or by inhibiting SOX2 expression. Thus, mutations in tumor suppressor genes can create a state of increased cellular plasticity that, when challenged with antiandrogen therapy, promotes resistance through lineage switching.
  date: 2017-1-6
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      link: https://pubmed.ncbi.nlm.nih.gov/28059768/
    - type: website
      link: https://www.science.org/doi/abs/10.1126/science.aah4307
  tags:
    - open science
    - collaboration

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
